"""Initial models: watchlist, news_article, article_symbol

Revision ID: 6f9da3cab2a7
Revises: 
Create Date: 2026-08-28 15:43:43.145355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f9da3cab2a7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_article',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('content_summary', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_news_article_published_at'), 'news_article', ['published_at'], unique=False)
    op.create_table('watchlist',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_index(op.f('ix_watchlist_symbol'), 'watchlist', ['symbol'], unique=False)
    op.create_table('article_symbol',
    sa.Column('article_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['news_article.id'], ),
    sa.ForeignKeyConstraint(['symbol'], ['watchlist.symbol'], ),
    sa.PrimaryKeyConstraint('article_id', 'symbol')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_symbol')
    op.drop_index(op.f('ix_watchlist_symbol'), table_name='watchlist')
    op.drop_table('watchlist')
    op.drop_index(op.f('ix_news_article_published_at'), table_name='news_article')
    op.drop_table('news_article')
    # ### end Alembic commands ###
