"""create_generated_report_table

Revision ID: af067c2d9943
Revises: 6f9da3cab2a7
Create Date: 2026-08-29 10:03:37.889367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af067c2d9943'
down_revision: Union[str, Sequence[str], None] = '6f9da3cab2a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_report',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('pdf_url', sa.String(length=1000), nullable=False),
    sa.Column('size_kb', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_report_created_at'), 'generated_report', ['created_at'], unique=False)
    op.create_index(op.f('ix_generated_report_report_type'), 'generated_report', ['report_type'], unique=False)
    op.create_index(op.f('ix_generated_report_symbol'), 'generated_report', ['symbol'], unique=False)
    op.drop_constraint(op.f('article_symbol_article_id_fkey'), 'article_symbol', type_='foreignkey')
    op.drop_constraint(op.f('article_symbol_symbol_fkey'), 'article_symbol', type_='foreignkey')
    op.create_foreign_key(None, 'article_symbol', 'news_article', ['article_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'article_symbol', 'watchlist', ['symbol'], ['symbol'], ondelete='CASCADE')
    op.create_index(op.f('ix_news_article_category'), 'news_article', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_article_category'), table_name='news_article')
    op.drop_constraint(None, 'article_symbol', type_='foreignkey')
    op.drop_constraint(None, 'article_symbol', type_='foreignkey')
    op.create_foreign_key(op.f('article_symbol_symbol_fkey'), 'article_symbol', 'watchlist', ['symbol'], ['symbol'])
    op.create_foreign_key(op.f('article_symbol_article_id_fkey'), 'article_symbol', 'news_article', ['article_id'], ['id'])
    op.drop_index(op.f('ix_generated_report_symbol'), table_name='generated_report')
    op.drop_index(op.f('ix_generated_report_report_type'), table_name='generated_report')
    op.drop_index(op.f('ix_generated_report_created_at'), table_name='generated_report')
    op.drop_table('generated_report')
    # ### end Alembic commands ###
